[package]
name = "imgfont"
author = "Madyan Al-hajebi"
version = "0.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/supax0/ImgFont"

[dependencies]
image = "0.23"
imageproc = "0.22.0"
rusttype = "0.9.2"
rayon = "1.5"
num_cpus = "1.13"
